/*
 * generated by Xtext
 */
package fr.istic.m2miage.idm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PollSystemRuntimeModule extends fr.istic.m2miage.idm.AbstractPollSystemRuntimeModule {

}
