package com.example.fr.istic.m2miage.idm.pollsystemandroid;

import android.content.Context;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.RadioGroup;
import android.widget.ScrollView;
import android.widget.TableLayout;

/**
	Generated by ModelToAndroid generator
*/
public class PollSystem1 extends ScrollView{
	
	private Context ctx;
	private TableLayout tableLayout;
	public PollSystem1(Context context) {
		super(context);
		this.ctx = context;
		
		tableLayout = new TableLayout(ctx);
		addView(tableLayout);
		
		// Poll System Title
		PollSystemUtils.addTextView(ctx, tableLayout, "PollSystem1");
		
		// Poll title
		PollSystemUtils.addTextView(ctx, tableLayout, "Poll 1 description");
		
		// Text question
		PollSystemUtils.addTextView(ctx, tableLayout, "Text Question 1");
		EditText tq1 = PollSystemUtils.addTextField(ctx, tableLayout);
		
		// Image question
		PollSystemUtils.addTextView(ctx, tableLayout, "Image Question 1");
		ImageView iviq1 = PollSystemUtils.addImageView(ctx, tableLayout, R.drawable.img2);// TODO
		EditText iq1 = PollSystemUtils.addTextField(ctx, tableLayout);
		
		// List question
		PollSystemUtils.addTextView(ctx, tableLayout, "Single Choice Question");
		RadioGroup rg1 = PollSystemUtils.addRadioGroup(ctx, tableLayout, "Option1", "Option2", "Option3");
		// Poll title
		PollSystemUtils.addTextView(ctx, tableLayout, "Poll 2 description");
		
		// Text question
		PollSystemUtils.addTextView(ctx, tableLayout, "Text Question 2");
		EditText tq2 = PollSystemUtils.addTextField(ctx, tableLayout);
		
		// Image question
		PollSystemUtils.addTextView(ctx, tableLayout, "Image Question");
		ImageView iviq2 = PollSystemUtils.addImageView(ctx, tableLayout, R.drawable.img1);// TODO
		EditText iq2 = PollSystemUtils.addTextField(ctx, tableLayout);
		
		// List question
		PollSystemUtils.addTextView(ctx, tableLayout, "Multiple Choice Question");
		CheckBox[] cb = PollSystemUtils.addCheckBox(ctx, tableLayout, "Option1", "Option2", "Option3");	
		
		Button btn = PollSystemUtils.addButton(ctx, tableLayout, "Save");
	}
}

