<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uimm" nsURI="http://idm.m2miage.istic.fr/uimm" nsPrefix="uimm">
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderStyle" eType="#//BorderStyle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bgColor" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageComponent" eSuperTypes="#//TextComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OptionType">
    <eLiterals name="Radio"/>
    <eLiterals name="CheckBox" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextComponent" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BorderStyle">
    <eLiterals name="Box"/>
    <eLiterals name="None" value="1"/>
    <eLiterals name="RoundedBox" value="2"/>
    <eLiterals name="Dotte" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color" instanceTypeName="Color">
    <eLiterals name="Azure"/>
    <eLiterals name="Cyan" value="1"/>
    <eLiterals name="LavenderBlush" value="2"/>
    <eLiterals name="LightGreen" value="3"/>
    <eLiterals name="PaleTurquoise" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListComponent" eSuperTypes="#//TextComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//OptionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
