package fr.istic.m2miage.idm.transformation.generator.android;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class UtilityClassGenerator {
  public static CharSequence createUtilityClass() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package com.example.fr.istic.m2miage.idm.pollsystemandroid;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import android.content.Context;");
    _builder.newLine();
    _builder.append("import android.view.View;");
    _builder.newLine();
    _builder.append("import android.widget.Button;");
    _builder.newLine();
    _builder.append("import android.widget.CheckBox;");
    _builder.newLine();
    _builder.append("import android.widget.EditText;");
    _builder.newLine();
    _builder.append("import android.widget.ImageView;");
    _builder.newLine();
    _builder.append("import android.widget.RadioButton;");
    _builder.newLine();
    _builder.append("import android.widget.RadioGroup;");
    _builder.newLine();
    _builder.append("import android.widget.ScrollView;");
    _builder.newLine();
    _builder.append("import android.widget.TableLayout;");
    _builder.newLine();
    _builder.append("import android.widget.TableLayout.LayoutParams;");
    _builder.newLine();
    _builder.append("import android.widget.TextView;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class PollSystemUtils {");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static void addComponent(ScrollView parent, View child){");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("parent.addView(child);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static RadioGroup addRadioGroup(Context ctx, TableLayout parent, String ...options){");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("RadioGroup rg = new RadioGroup(ctx);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for(String o : options){");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("RadioButton rb = new RadioButton(ctx);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("rb.setText(o);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("rg.addView(rb);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("parent.addView(rg);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return rg;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static void addTextView(Context ctx, TableLayout parent, String text){");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("TextView tv = new TextView(ctx);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("tv.setText(text);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("parent.addView(tv);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static EditText addTextField(Context ctx, TableLayout parent){");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("EditText et = new EditText(ctx);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("parent.addView(et);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return et;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static ImageView addImageView(Context ctx, TableLayout parent, int questionImage1){");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ImageView iv = new ImageView(ctx);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("iv.setImageResource(questionImage1);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("LayoutParams params = new LayoutParams();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("params.height =500;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("iv.setLayoutParams(params);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("parent.addView(iv);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return iv;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static CheckBox[] addCheckBox(Context ctx, TableLayout parent, String ...options) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int cnt = options.length;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("CheckBox[] cbx = new CheckBox[cnt];");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int i = 0;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for(String o : options){");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("cbx[i] = new CheckBox(ctx);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("cbx[i].setText(o);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("parent.addView(cbx[i]);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("i++;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return cbx;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static Button addButton(Context ctx, TableLayout parent, String text) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Button btn = new Button(ctx);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("btn.setText(text);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("parent.addView(btn);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return btn;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
