/**
 * generated by Xtext
 */
package fr.istic.m2miage.idm.validation;

import fr.istic.m2miage.idm.validation.AbstractCSSValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CSSValidator extends AbstractCSSValidator {
}
